### ISSUE TITLE
Linux and Mac support

### ISSUE THREAD

**Issue by warriormaster12** [puchik/godot-extras#2]
Hi, I noticed that the compiled project uses lod.dll file. Just want to ask, is the project platform agnostic or is there platform specific code?

**Comment by puchik** [comment]
It should be platform agnostic. In fact I would appreciate testers for other platforms. I may upload the Linux specific compiled binary myself at some point.

**Comment by warriormaster12** [comment]
Mm !! I'll try compile with Scons.
